<a href="https://colab.research.google.com/github/rodrigobivarazevedo/cs50ai/blob/master/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


# save filepath to variable for easier access
melbourne_file_path = 'melb_data.csv'
# read the data and store data in DataFrame titled melbourne_data
melbourne_data = pd.read_csv(melbourne_file_path)

In [ ]:
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [ ]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [ ]:
melbourne_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [ ]:
melbourne_data.columns.unique()

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [ ]:
melbourne_data = melbourne_data.dropna(axis=0)
melbourne_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6196 entries, 1 to 12212
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         6196 non-null   object
 1   Address        6196 non-null   object
 2   Rooms          6196 non-null   int64
 3   Type           6196 non-null   object
 4   Price          6196 non-null   float64
 5   Method         6196 non-null   object
 6   SellerG        6196 non-null   object
 7   Date           6196 non-null   object
 8   Distance       6196 non-null   float64
 9   Postcode       6196 non-null   float64
 10  Bedroom2       6196 non-null   float64
 11  Bathroom       6196 non-null   float64
 12  Car            6196 non-null   float64
 13  Landsize       6196 non-null   float64
 14  BuildingArea   6196 non-null   float64
 15  YearBuilt      6196 non-null   float64
 16  CouncilArea    6196 non-null   object
 17  Lattitude      6196 non-null   float64
 18  Longtitude     6196 non-null   float64
 19  Regionname     6196 non-null   object
 20  Propertycount  6196 non-null   float64
dtypes: float64(12), int64(1), object(8)
memory usage: 1.0+ MB

In [ ]:
melbourne_features = ['Rooms', 'Type', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount']

In [ ]:
# select data corresponding to features in melbourne_features
X = melbourne_data[melbourne_features]
# select data corresponding to the Price
y = melbourne_data.Price

In [ ]:
X.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (6196, 13)
Shape of y: (6196,)

In [ ]:
X.head()

,Rooms,Type,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
1,2,h,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.8079,144.9934,4019.0
2,3,h,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.8093,144.9944,4019.0
4,4,h,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.8072,144.9941,4019.0
6,3,h,2.5,3067.0,4.0,2.0,0.0,245.0,210.0,1910.0,-37.8024,144.9993,4019.0
7,2,h,2.5,3067.0,2.0,1.0,2.0,256.0,107.0,1890.0,-37.8060,144.9954,4019.0

In [ ]:
# one-hot encoding via pandas

pandas_encoded = pd.get_dummies(X, dtype=int)

In [ ]:
pandas_encoded.head()

,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount,Type_h,Type_t,Type_u
1,2,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,-37.8079,144.9934,4019.0,1,0,0
2,3,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,-37.8093,144.9944,4019.0,1,0,0
4,4,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,-37.8072,144.9941,4019.0,1,0,0
6,3,2.5,3067.0,4.0,2.0,0.0,245.0,210.0,1910.0,-37.8024,144.9993,4019.0,1,0,0
7,2,2.5,3067.0,2.0,1.0,2.0,256.0,107.0,1890.0,-37.8060,144.9954,4019.0,1,0,0

In [ ]:
pandas_encoded.shape

(6196, 15)

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Separate the column to encode
X_to_encode = X[['Type']]

# Initialize the OneHotEncoder
onehot_encoder = OneHotEncoder()

# Fit and transform the column to encode
type_encoded = onehot_encoder.fit_transform(X_to_encode)

# Convert the sparse matrix to a DataFrame
encoded_df = pd.DataFrame.sparse.from_spmatrix(type_encoded, columns=onehot_encoder.categories_[0])

# Concatenate the original DataFrame and the encoded DataFrame
X_encoded = pd.concat([X.drop(columns=['Type']), encoded_df], axis=1)

# Print the shapes to verify
print("Original X shape:", X.shape)
print("Encoded X shape:", X_encoded.shape)
print("Encoded X shape:", X_encoded.info())

Original X shape: (6196, 13)
Encoded X shape: (9043, 15)
<class 'pandas.core.frame.DataFrame'>
Index: 9043 entries, 1 to 6195
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rooms          6196 non-null   float64
 1   Distance       6196 non-null   float64
 2   Postcode       6196 non-null   float64
 3   Bedroom2       6196 non-null   float64
 4   Bathroom       6196 non-null   float64
 5   Car            6196 non-null   float64
 6   Landsize       6196 non-null   float64
 7   BuildingArea   6196 non-null   float64
 8   YearBuilt      6196 non-null   float64
 9   Lattitude      6196 non-null   float64
 10  Longtitude     6196 non-null   float64
 11  Propertycount  6196 non-null   float64
 12  h              6196 non-null   Sparse[float64, 0]
 13  t              6196 non-null   Sparse[float64, 0]
 14  u              6196 non-null   Sparse[float64, 0]
dtypes: Sparse[float64, 0](3), float64(12)
memory usage: 1.1 MB
Encoded X shape: None

In [ ]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (6196, 13)
Shape of y: (6196,)

In [ ]:
# sequential feature selection

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

feat_labels = ['Rooms', "Type", 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount']

forest = RandomForestClassifier(n_estimators=500, random_state=1)
# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(pandas_encoded, y, random_state=0)

forest.fit(X_train, y_train)
importances = forest.feature_importances_

indices = np.argsort(importances)[::-1]

for f in range(X_train.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30,
                            feat_labels[indices[f]],
                            importances[indices[f]]))

plt.title('Feature Importance')
plt.bar(range(X_train.shape[1]),
        importances[indices],
        align='center')

plt.xticks(range(X_train.shape[1]),
           feat_labels[indices], rotation=90)
plt.xlim([-1, X_train.shape[1]])
plt.tight_layout()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Assuming X and y are already defined and contain your features and target variable
melbourne_features = ['Rooms', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount']
# select data corresponding to features in melbourne_features
X = melbourne_data[melbourne_features]
y = melbourne_data.Price

# Split data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)

# Define the Random Forest model
forest_model = RandomForestRegressor(
    n_estimators=1000,   # Number of trees in the forest
    criterion='squared_error',    # Criterion for splitting: Mean Squared Error
    random_state=1,     # Random seed for reproducibility
    n_jobs=-1           # Use all available CPU cores
)

# Train the model on the training data
forest_model.fit(train_X, train_y)

# Make predictions on the validation data
val_predictions = forest_model.predict(val_X)

# Calculate and print the Mean Absolute Error (MAE)
mae = mean_absolute_error(val_y, val_predictions)
print("Validation MAE for Random Forest Model: {}".format(mae))

Validation MAE for Random Forest Model: 181589.06272313936

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error


# Split data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(pandas_encoded, y, random_state=0)

# Define the Random Forest model
forest_model = RandomForestRegressor(
    n_estimators=500,   # Number of trees in the forest
    max_depth=791,
    criterion='squared_error',    # Criterion for splitting: Mean Squared Error
    random_state=1,     # Random seed for reproducibility
    n_jobs=-1           # Use all available CPU cores
)

# Train the model on the training data
forest_model.fit(train_X, train_y)

# Make predictions on the validation data
val_predictions = forest_model.predict(val_X)

# Calculate and print the Mean Absolute Error (MAE)
mae = mean_absolute_error(val_y, val_predictions)
print("Validation MAE for Random Forest Model: {}".format(mae))

Validation MAE for Random Forest Model: 178958.3316592374

In [ ]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
import numpy as np

# Assuming pandas_encoded and y are your features and target variables

# Split data into training and validation sets
train_X, val_X, train_y, val_y = train_test_split(pandas_encoded, y, random_state=0)

# Define the Random Forest model
forest_model = RandomForestRegressor(random_state=1, n_jobs=-1)

# Define the parameter grid to search through
param_grid = {
    'n_estimators': [100, 200, 300, 400, 500, 600, 700],  # Number of trees in the forest
    'max_depth': [None, 10, 50, 100, 200, 500, 600, 700],  # Maximum depth of each tree
    'min_samples_split': [2, 5, 10],  # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4],  # Minimum number of samples required to be at a leaf node
    'max_features': ['auto', 'sqrt', 'log2'],  # Number of features to consider at each split
    'bootstrap': [True, False]  # Whether bootstrap samples are used when building trees
}

# Perform RandomizedSearchCV to find the best parameters
rf_random = RandomizedSearchCV(estimator=forest_model, param_distributions=param_grid,
                               n_iter=100, cv=3, verbose=2, random_state=42, n_jobs=-1)

# Fit the RandomizedSearchCV instance
rf_random.fit(train_X, train_y)

# Get the best parameters found by RandomizedSearchCV
print("Best parameters found by RandomizedSearchCV:")
print(rf_random.best_params_)

# Make predictions on the validation data using the best model found
val_predictions = rf_random.best_estimator_.predict(val_X)

# Calculate and print the Mean Absolute Error (MAE)
mae = mean_absolute_error(val_y, val_predictions)
print("\nValidation MAE for Random Forest Model after hyperparameter tuning: {:.2f}".format(mae))

Fitting 3 folds for each of 100 candidates, totalling 300 fits

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:547: FitFailedWarning:
108 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
55 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1467, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
53 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1467, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:1051: UserWarning: One or more of the test scores are non-finite: [0.82223671        nan        nan 0.83096719 0.82556979 0.81669243
        nan 0.8303758         nan        nan        nan 0.80835122
 0.82030579        nan        nan        nan        nan        nan
 0.81512759 0.82068534 0.81464256 0.81071439 0.83061411 0.83127549
 0.80446366 0.82246513 0.81746207 0.82562134        nan 0.80963683
        nan 0.8272564  0.82120194 0.81512781        nan 0.82100592
 0.82547415 0.8223122  0.8261567  0.8260981  0.83536943 0.82256646
 0.81968772 0.82752213        nan 0.82585669 0.82068534        nan
 0.80220183        nan 0.80905324 0.80182907        nan        nan
 0.82752213        nan 0.81190867 0.83499082 0.82100592 0.83064801
 0.82764033 0.82115149        nan        nan        nan 0.8272564
 0.81448041 0.83122122 0.81458122        nan 0.80210768 0.81322355
        nan        nan        nan        nan 0.82246513 0.80579449
 0.81217753 0.82242178        nan        nan 0.83524282        nan
 0.80982405 0.82163854        nan        nan 0.82198203        nan
        nan 0.82579945        nan 0.83122122 0.82120194 0.81448041
 0.82198203 0.80568748 0.82248197 0.8261567 ]
  warnings.warn(

Best parameters found by RandomizedSearchCV:
{'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 50, 'bootstrap': False}

Validation MAE for Random Forest Model after hyperparameter tuning: 174497.05